# Generated by Django 2.2.6 on 2019-10-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schuljahr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schuljahr', models.IntegerField(verbose_name='Schuljahr')),
            ],
        ),
    ]
