# Generated by Django 2.2.6 on 2019-10-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verwaltung', '0004_teilnahme_schuljahr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schuljahr',
            options={'verbose_name': 'Schuljahr', 'verbose_name_plural': 'Schuljahre'},
        ),
        migrations.AlterField(
            model_name='aktivitaetergebnis',
            name='mint_punkte',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='MINT-EC-Punkte'),
        ),
    ]
